[tool.poetry]
authors = ["Ken Van Haren <kvh@getbasis.com>"]
description = "Data pipelines from re-usable components"
license = "BSD-3-Clause"
name = "basis-devkit"
packages = [
  {include = "basis"},
]
version = "0.1.0"

[tool.poetry.dependencies]
cleo = "^0.8.1"
common-model = "~0.2.0"
cookiecutter = "^1.7.3"
datacopy = "~0.3.0"
jinja2 = "^3.0.0"
pyarrow = "^5.0.0"
pydantic = "^1.8.1"
python = "^3.7.4"
requests-mock = "^1.9.3"
strictyaml = "^1.0.6"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
# common-model = {path = "../common-model/python", develop = true}
# datacopy = {path = "../dcp", develop = true}
flake8 = "^3.8.1"
ipython = "^7.13.0"
isort = "^4.3.21"
mkdocs = "^1.1.2"
mkdocs-material = "^6.1.7"
mypy = "^0.770"
pre-commit = "^2.1.1"
psycopg2-binary = "^2.8.6"
pydeps = "^1.9.0"
pytest = "^4.6"
pytest-cov = "^2.8.1"
sqlalchemy-stubs = "^0.3"

[tool.poetry.scripts]
basis = "basis.cli:app"

[tool.black]
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.pytest_cache
  | \.tox
  | \.venv
  | build
  | dist
  | basis/cli/templates/templates
)/
'''

[tool.isort]
force_grid_wrap = 0
include_trailing_comma = true
line_length = 88
multi_line_output = 3
skip_glob = "examples/*"
use_parentheses = true

[tool.pytest.ini_options]
addopts = "-ra -q"
norecursedirs = []
testpaths = [
  "tests",
]

[build-system]
build-backend = "poetry.masonry.api"
requires = ["poetry>=0.12"]
