name: "example-prod"
storages:
  - name: storage1
    url: ${{ secrets.storage1 }}
  - name: storage2
    url: ${{ secrets.storage2 }}
default_storage: storage1
graph:
  - name: app1 # Can specify app configs
    app: app1/app1.yml
    app_params:
      # Override app params here
      limit: 200
  - name: app2
    app: app2/app2.yml
  # Option?
  # - key: node1 # Or individual nodes
  #   component: import_stripe
  #   params:
  #     resources:
  #       - transactions
  #       - refunds










basis-api-nonprod basis-vpc-host-nonprod basis-logging-nonprod basis-monitoring-prod basis-monitoring-nonprod basis-vpc-host-prod

gcloud config set project basis-api-nonprod
gcloud services enable bigtableadmin.googleapis.com firestore.googleapis.com iam.googleapis.com spanner.googleapis.com sqladmin.googleapis.com
gcloud config set project basis-vpc-host-nonprod
gcloud services enable bigtableadmin.googleapis.com firestore.googleapis.com iam.googleapis.com spanner.googleapis.com sqladmin.googleapis.com
gcloud config set project basis-logging-nonprod
gcloud services enable bigtableadmin.googleapis.com firestore.googleapis.com iam.googleapis.com spanner.googleapis.com sqladmin.googleapis.com
gcloud config set project basis-monitoring-prod
gcloud services enable bigtableadmin.googleapis.com firestore.googleapis.com iam.googleapis.com spanner.googleapis.com sqladmin.googleapis.com
gcloud config set project basis-monitoring-nonprod
gcloud services enable bigtableadmin.googleapis.com firestore.googleapis.com iam.googleapis.com spanner.googleapis.com sqladmin.googleapis.com
gcloud config set project basis-vpc-host-prod
gcloud services enable bigtableadmin.googleapis.com firestore.googleapis.com iam.googleapis.com spanner.googleapis.com sqladmin.googleapis.com
gcloud config set project basis-vpc-host-nonprod basis-logging-nonprod basis-monitoring-prod basis-monitoring-nonprod basis-vpc-host-prod
gcloud services enable bigtableadmin.googleapis.com firestore.googleapis.com iam.googleapis.com spanner.googleapis.com
gcloud config set project basis-vpc-host-nonprod basis-logging-nonprod basis-monitoring-prod basis-monitoring-nonprod basis-vpc-host-prod
gcloud services enable bigtableadmin.googleapis.com firestore.googleapis.com iam.googleapis.com spanner.googleapis.com
gcloud config set project basis-vpc-host-nonprod basis-logging-nonprod basis-monitoring-prod basis-monitoring-nonprod basis-vpc-host-prod
gcloud services enable bigtableadmin.googleapis.com firestore.googleapis.com iam.googleapis.com spanner.googleapis.com