name: "example-prod"
storages:
  - name: storage1
    url: ${{ secrets.storage1 }}
  - name: storage2
    url: ${{ secrets.storage2 }}
default_storage: storage1
graph:
  - name: app1 # Can specify app configs
    app: app1/app1.yml
    app_params:
      # Override app params here
      limit: 200
  - name: app2
    app: app2/app2.yml
  # Option?
  # - key: node1 # Or individual nodes
  #   component: import_stripe
  #   params:
  #     resources:
  #       - transactions
  #       - refunds
